### home
GET http://localhost:3000/ HTTP/1.1
Set-Cookie: id=XS12;Secure;httpOnly

### resources test
GET http://127.0.0.1:3000/resources/7777.png HTTP/1.1

### 
GET http://127.0.0.1:3000/ HTTP/1.1

### users
GET http://localhost:3000/users HTTP/1.1
Connection : keep-alive

### get user data
GET http://localhost:3000/users/mohamed_elkony HTTP/1.1
Connection : keep-alive

### get inventory 
GET http://localhost:3000/inventory HTTP/1.1
Connection : keep-alive
Content-Type: application/json

{
    "limit":5
}

### add product to shopping cart
POST http://localhost:3000/inventory/cart HTTP/1.1
Connection : keep-alive
Content-Type: application/json

{
    "product_id":2
}


###get user log
GET http://localhost:3000/users/log/mohamed_elkony HTTP/1.1
Connection:  keep-alive

### go to user profile
GET http://localhost:3000/profile/mohamed_elkony HTTP/1.1
Connection : keep-alive


### new user
POST http://127.0.0.1:3000/users HTTP/1.1
Content-Type: application/json

{
    "username": "omar",
    "email": "omar@momar.com",
    "birth": "1997-03-07",
    "password": "123456789" ,
    "gender":"male",
    "repassword":"123456789"
}
### login 
POST http://127.0.0.1:3000/login HTTP/1.1
Content-Type: application/json
Connection : keep-alive

{
    "email":"omar@momar.com",
    "password":"123456789"
}

###home
GET http://localhost:3000 HTTP/1.1


###logout
GET http://localhost:3000/logout HTTP/1.1



