- name: Ensure required dependencies are installed
  ansible.builtin.package:
    name:
      - openjdk-11-jdk
    state: present

- name: Verify Java installation
  ansible.builtin.command: java -version
  register: java_version_check
  ignore_errors: yes

- name: Debug Java version
  ansible.builtin.debug:
    var: java_version_check.stdout