pipeline {
    agent none
    stages {
        stage('Provision EC2 Instance') {
            agent {
                label "Controller" 
            }
            stages{
                stage('Create jenkins agent EC2 instance'){
                    steps {
                        // Create an EC2 instance using Terraform
                        checkout scm // #TODO Fetches entire repo although only CI-CD folder is needed (check for better design)

                        // agent EC2 instance private key is static key in AWS and jenkis controller                    
                        withCredentials([sshUserPrivateKey(
                            credentialsId: 'Jenkis_agent_EC2_private_key',
                            keyFileVariable: 'Jenkis_agent_EC2_private_key_Path',
                            usernameVariable: 'Jenkis_agent_EC2_private_key_Username' 
                        )]) {

                        dir ('CI-CD') {
                        
                            sh """
                                ansible-playbook provision_jenkins_agent_EC2_instance.yml -vvv 
                                -e "private_key_path=${Jenkis_agent_EC2_private_key_Path}"
                                -e "EC2_instance_ssh_username=${Jenkis_agent_EC2_private_key_Username}"
                                -e "jenkins_controller_ip=54.193.5.178"
                            """
                        }

                        // read IP address of the instance via file and pass it to jenkins

                        //create new agent with IP and key

                    }    
            
                }
                stage('Build E-commerce web application') {
                    steps {
                        echo '==================='
                        sh 'ls -la'
                    }
                }
            }
        }
    }
}